### ISSUE TITLE
routes.js

### ISSUE THREAD

**Issue by jrans** [lajj/pen.js#14]
Code crystal has demonstarted that routes.js is not required by your backend and therefore may be redundant?

**Comment by jrans** [comment]
and handlers.js

**Comment by jrans** [comment]
![screen shot 2015-06-26 at 11 45 40](https://cloud.githubusercontent.com/assets/12045918/8375848/08b2478e-1bf9-11e5-8484-6f7bbd270bd8.png)

**Comment by Lukars** [comment]
thats true - removed them, thanks
